name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: codingloha321/fast-api-reaction
          stage: main
          yaml: |
            name: fastapi
            app: python@3.9
            options:
              env:
                - name: POSTGRESQL_ENDPOINT
                  value: postgres
                - name: POSTGRESQL_PORT
                  value: "5432"
                - name: POSTGRESQL_TABLE
                  value: reaction_db
                - name: POSTGRESQL_USER
                  value: root
                - name: POSTGRESQL_PASSWORD
                  value: "3321"
              ports: 8000
              start: uvicorn main:app --host=0.0.0.0 --port=8000
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: python-fastapi
